spring:
  datasource:
    url: jdbc:mysql://192.168.56.101/jpa
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true